export const APP_IS_READY_REQUEST = "APP_IS_READY_REQUEST";
export const APP_IS_READY_RESPONSE = "APP_IS_READY_RESPONSE";

export const CONNECTION_REQUEST_MESSAGE = "CONNECTION_REQUEST";
export const CONNECTION_RESPONSE_MESSAGE = "CONNECTION_RESPONSE";

export const IS_SESSION_VALID_REQUEST = "IS_SESSION_VALID_REQUEST";
export const IS_SESSION_VALID_RESPONSE = "IS_SESSION_VALID_RESPONSE";

export const CHECK_CONNECTION_REQUEST = "CHECK_CONNECTION_REQUEST";

export const NEW_ACCOUNT_REQUEST = "NEW_ACCOUNT_REQUEST";
export const NEW_ACCOUNT_RESPONSE = "NEW_ACCOUNT_RESPONSE";

export const TRANSFER_REQUEST = "TRANSFER_REQUEST";
export const TRANSFER_RESPONSE = "TRANSFER_RESPONSE";

export const DISCONNECT_REQUEST = "DISCONNECT_REQUEST";
export const DISCONNECT_RESPONSE = "DISCONNECT_RESPONSE";

export const LIST_ACCOUNTS_REQUEST = "LIST_ACCOUNTS_REQUEST";
export const LIST_ACCOUNTS_RESPONSE = "LIST_ACCOUNTS_RESPONSE";

export const SELECTED_CHAIN_CHANGED = "SELECTED_CHAIN_CHANGED";
export const SELECTED_ACCOUNT_CHANGED = "SELECTED_ACCOUNT_CHANGED";

export const EXTERNAL_ACCOUNT_BALANCE_REQUEST =
  "EXTERNAL_ACCOUNT_BALANCE_REQUEST";
export const EXTERNAL_ACCOUNT_BALANCE_RESPONSE =
  "EXTERNAL_ACCOUNT_BALANCE_RESPONSE";

export const SELECTED_CHAIN_REQUEST = "SELECTED_CHAIN_REQUEST";
export const SELECTED_CHAIN_RESPONSE = "SELECTED_CHAIN_RESPONSE";

export const GET_POKT_TRANSACTION_REQUEST = "GET_POKT_TRANSACTION_REQUEST";
export const GET_POKT_TRANSACTION_RESPONSE = "GET_POKT_TRANSACTION_RESPONSE";

export const SWITCH_CHAIN_REQUEST = "SWITCH_CHAIN_REQUEST";
export const SWITCH_CHAIN_RESPONSE = "SWITCH_CHAIN_RESPONSE";

export const SIGN_TYPED_DATA_REQUEST = "SIGN_TYPED_DATA_REQUEST";
export const SIGN_TYPED_DATA_RESPONSE = "SIGN_TYPED_DATA_RESPONSE";

export const PERSONAL_SIGN_REQUEST = "PERSONAL_SIGN_REQUEST";
export const PERSONAL_SIGN_RESPONSE = "PERSONAL_SIGN_RESPONSE";

// internal

export const ANSWER_CONNECTION_REQUEST = "ANSWER_CONNECTION_REQUEST";
export const ANSWER_CONNECTION_RESPONSE = "ANSWER_CONNECTION_RESPONSE";

export const ANSWER_SWITCH_CHAIN_REQUEST = "ANSWER_SWITCH_CHAIN_REQUEST";
export const ANSWER_SWITCH_CHAIN_RESPONSE = "ANSWER_SWITCH_CHAIN_RESPONSE";

export const ANSWER_SIGNED_TYPED_DATA_REQUEST =
  "ANSWER_SIGNED_TYPED_DATA_REQUEST";
export const ANSWER_SIGNED_TYPED_DATA_RESPONSE =
  "ANSWER_SIGNED_TYPED_DATA_REQUEST";

export const ANSWER_PERSONAL_SIGN_REQUEST = "ANSWER_PERSONAL_SIGN_REQUEST";
export const ANSWER_PERSONAL_SIGN_RESPONSE = "ANSWER_PERSONAL_SIGN_RESPONSE";

export const ANSWER_NEW_ACCOUNT_REQUEST = "ANSWER_NEW_ACCOUNT_REQUEST";
export const ANSWER_NEW_ACCOUNT_RESPONSE = "ANSWER_NEW_ACCOUNT_RESPONSE";

export const ANSWER_TRANSFER_REQUEST = "ANSWER_TRANSFER_REQUEST";
export const ANSWER_TRANSFER_RESPONSE = "ANSWER_TRANSFER_RESPONSE";

export const INITIALIZE_VAULT_REQUEST = "INITIALIZE_VAULT_REQUEST";
export const INITIALIZE_VAULT_RESPONSE = "INITIALIZE_VAULT_RESPONSE";

export const UNLOCK_VAULT_REQUEST = "UNLOCK_VAULT_REQUEST";
export const UNLOCK_VAULT_RESPONSE = "UNLOCK_VAULT_RESPONSE";

export const LOCK_VAULT_REQUEST = "LOCK_VAULT_REQUEST";
export const LOCK_VAULT_RESPONSE = "LOCK_VAULT_RESPONSE";

export const REVOKE_SESSION_REQUEST = "REVOKE_SESSION_REQUEST";
export const REVOKE_SESSION_RESPONSE = "REVOKE_SESSION_RESPONSE";

export const REVOKE_EXTERNAL_SESSIONS_REQUEST =
  "REVOKE_EXTERNAL_SESSIONS_REQUEST";
export const REVOKE_EXTERNAL_SESSIONS_RESPONSE =
  "REVOKE_EXTERNAL_SESSIONS_RESPONSE";

export const UPDATE_ACCOUNT_REQUEST = "UPDATE_ACCOUNT_REQUEST";
export const UPDATE_ACCOUNT_RESPONSE = "UPDATE_ACCOUNT_RESPONSE";

export const UPDATE_RECOVERY_PHRASE_REQUEST = "UPDATE_RECOVERY_PHRASE_REQUEST";
export const UPDATE_RECOVERY_PHRASE_RESPONSE =
  "UPDATE_RECOVERY_PHRASE_RESPONSE";

export const REMOVE_ACCOUNT_REQUEST = "REMOVE_ACCOUNT_REQUEST";
export const REMOVE_ACCOUNT_RESPONSE = "REMOVE_ACCOUNT_RESPONSE";

export const REMOVE_RECOVERY_PHRASE_REQUEST = "REMOVE_RECOVERY_PHRASE_REQUEST";
export const REMOVE_RECOVERY_PHRASE_RESPONSE =
  "REMOVE_RECOVERY_PHRASE_RESPONSE";

export const IMPORT_ACCOUNT_REQUEST = "IMPORT_ACCOUNT_REQUEST";
export const IMPORT_ACCOUNT_RESPONSE = "IMPORT_ACCOUNT_RESPONSE";

export const PK_ACCOUNT_REQUEST = "PK_ACCOUNT_REQUEST";
export const PK_ACCOUNT_RESPONSE = "PK_ACCOUNT_RESPONSE";

export const ACCOUNT_BALANCE_REQUEST = "ACCOUNT_BALANCE_REQUEST";
export const ACCOUNT_BALANCE_RESPONSE = "ACCOUNT_BALANCE_RESPONSE";

export const NETWORK_FEE_REQUEST = "NETWORK_FEE_REQUEST";
export const NETWORK_FEE_RESPONSE = "NETWORK_FEE_RESPONSE";

export const CHECK_PERMISSION_FOR_SESSION_REQUEST =
  "CHECK_PERMISSION_FOR_SESSION_REQUEST";
export const CHECK_PERMISSION_FOR_SESSION_RESPONSE =
  "CHECK_PERMISSION_FOR_SESSION_RESPONSE";

export const APP_IS_NOT_READY = "APP_IS_NOT_READY";
export const APP_IS_READY = "APP_IS_READY";

export const EXPORT_VAULT_REQUEST = "EXPORT_VAULT_REQUEST";
export const EXPORT_VAULT_RESPONSE = "EXPORT_VAULT_RESPONSE";

export const SHOULD_EXPORT_VAULT_REQUEST = "SHOULD_EXPORT_VAULT_REQUEST";
export const SHOULD_EXPORT_VAULT_RESPONSE = "SHOULD_EXPORT_VAULT_RESPONSE";

export const IMPORT_VAULT_REQUEST = "IMPORT_VAULT_REQUEST";
export const IMPORT_VAULT_RESPONSE = "IMPORT_VAULT_RESPONSE";

export const SET_REQUIRE_PASSWORD_FOR_OPTS_REQUEST =
  "SET_REQUIRE_PASSWORD_FOR_OPTS_REQUEST";
export const SET_REQUIRE_PASSWORD_FOR_OPTS_RESPONSE =
  "SET_REQUIRE_PASSWORD_FOR_OPTS_RESPONSE";

export const IMPORT_HD_WALLET_REQUEST = "IMPORT_HD_WALLET_REQUEST";
export const IMPORT_HD_WALLET_RESPONSE = "IMPORT_HD_WALLET_RESPONSE";

export const GET_RECOVERY_PHRASE_ID_REQUEST = "GET_RECOVERY_PHRASE_ID_REQUEST";
export const GET_RECOVERY_PHRASE_ID_RESPONSE =
  "GET_RECOVERY_PHRASE_ID_RESPONSE";

export const CREATE_ACCOUNT_FROM_HD_SEED_REQUEST =
  "CREATE_ACCOUNT_FROM_HD_SEED_REQUEST";
export const CREATE_ACCOUNT_FROM_HD_SEED_RESPONSE =
  "CREATE_ACCOUNT_FROM_HD_SEED_RESPONSE";

export const PHRASE_GENERATED_HD_SEED_REQUEST =
  "PHRASE_GENERATED_HD_SEED_REQUEST";
export const PHRASE_GENERATED_HD_SEED_RESPONSE =
  "PHRASE_GENERATED_HD_SEED_RESPONSE";

// background
export const REQUEST_BEING_HANDLED = "REQUEST_BEING_HANDLED";

export const MINUTES_ALLOWED_FOR_REQ = 5;

export const EIP6963EthAnnounceType = "eip6963:announceProvider";
export const PocketAnnounceType = "pocket:announceProvider";

export const EIP6963EthRequestType = "eip6963:requestProvider";
export const PocketRequestType = "pocket:requestProvider";
