export const CONNECTION_REQUEST_MESSAGE = "CONNECTION_REQUEST";
export const CONNECTION_RESPONSE_MESSAGE = "CONNECTION_RESPONSE";

export const IS_SESSION_VALID_REQUEST = "IS_SESSION_VALID_REQUEST";
export const IS_SESSION_VALID_RESPONSE = "IS_SESSION_VALID_RESPONSE";

export const CHECK_CONNECTION_REQUEST = "CHECK_CONNECTION_REQUEST";

export const NEW_ACCOUNT_REQUEST = "NEW_ACCOUNT_REQUEST";
export const NEW_ACCOUNT_RESPONSE = "NEW_ACCOUNT_RESPONSE";

export const TRANSFER_REQUEST = "TRANSFER_REQUEST";
export const TRANSFER_RESPONSE = "TRANSFER_RESPONSE";

// internal

export const ANSWER_CONNECTION_REQUEST = "ANSWER_CONNECTION_REQUEST";
export const ANSWER_CONNECTION_RESPONSE = "ANSWER_CONNECTION_RESPONSE";

export const ANSWER_NEW_ACCOUNT_REQUEST = "ANSWER_NEW_ACCOUNT_REQUEST";
export const ANSWER_NEW_ACCOUNT_RESPONSE = "ANSWER_NEW_ACCOUNT_RESPONSE";

export const ANSWER_TRANSFER_REQUEST = "ANSWER_TRANSFER_REQUEST";
export const ANSWER_TRANSFER_RESPONSE = "ANSWER_TRANSFER_RESPONSE";

export const INITIALIZE_VAULT_REQUEST = "INITIALIZE_VAULT_REQUEST";
export const INITIALIZE_VAULT_RESPONSE = "INITIALIZE_VAULT_RESPONSE";

export const UNLOCK_VAULT_REQUEST = "UNLOCK_VAULT_REQUEST";
export const UNLOCK_VAULT_RESPONSE = "UNLOCK_VAULT_RESPONSE";

export const LOCK_VAULT_REQUEST = "LOCK_VAULT_REQUEST";
export const LOCK_VAULT_RESPONSE = "LOCK_VAULT_RESPONSE";

export const REVOKE_SESSION_REQUEST = "REVOKE_SESSION_REQUEST";
export const REVOKE_SESSION_RESPONSE = "REVOKE_SESSION_RESPONSE";

// background
export const REQUEST_BEING_HANDLED = "REQUEST_BEING_HANDLED";
