#!/bin/sh

# We need to update the @lavamoat/webpack package to the latest version
# because the version released at npm does not support scuttle yet.

set -e

DIR="$(dirname "$0")"
if [ ! -d "$DIR" ]; then
  DIR="$PWD"
fi
DIR="$(cd "$DIR" && pwd)"

. ${DIR}/shared.sh

# Create a temp directory to clone lavamoat into
WORK_DIR=$(mktemp -d -p "${DIR}")
# Normalize WORK_DIR to absolute path
WORK_DIR=$(cd "$WORK_DIR" && pwd)

if [ -z "$WORK_DIR" ]; then
  error_log "Could not create temp dir"
  exit 1
fi

info_log "Working in $WORK_DIR"

cleanup() {
  info_log "Cleaning up..."
  rm -rf "$WORK_DIR"
  info_log "Cleanup done. LavaMoat directory was deleted."
}

# Remove the temp directory on exit
trap cleanup EXIT

default_branch="main"
branch=${1:-$default_branch}

cd ${WORK_DIR}

info_log "Cloning LavaMoat from github.com/LavaMoat/lavamoat..."
git clone https://github.com/LavaMoat/LavaMoat.git

info_log "LavaMoat from github.com/LavaMoat/lavaMoat was cloned."

if [ "$branch" != "$default_branch" ]; then
  info_log "Checking out $branch branch in LavaMoat repository..."
  cd LavaMoat
  git checkout $branch
  cd ..
fi

# Deleting old LavaMoat webpack files.
rm -rf ${DIR}/../../../../node_modules/@lavamoat/webpack/src

# Here we are copying the files from poktroll.application because every directory has the types directory with the same files inside generated by ignite.
cp -TR LavaMoat/packages/webpack/src ${DIR}/../../../../node_modules/@lavamoat/webpack/src

info_log "LavaMoat webpack files were copied."



