name: Pre Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  create-pre-release:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Load env file
        run: |
          echo "${{vars.ENV_FILE}}" > apps/nodejs/extension/.env
      # source code attached to release will never have untracked files
      - name: Archive source with env files
        run: |
          git ls-files > tar-include.txt
          echo "apps/nodejs/extension/.env" >> tar-include.txt
          tar -czf source-with-envs-${{ steps.version.outputs.value }}.tar.gz -T tar-include.txt
      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies
        run: yarn
      - name: Version Packages
        run: yarn changeset version
      - name: Build Extension Dependencies
        run: yarn turbo run build --filter=\!@soothe/extension
      - name: Prepare Chromium Release Asset
        run: yarn release:chromium
      - name: Prepare Firefox Release Asset
        run: yarn release:firefox
      - name: Extract Extension Package Version
        uses: sergeysova/jq-action@v2.3.0
        id: version
        with:
          cmd: 'jq .version apps/nodejs/extension/package.json -r'
      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: rc-${{ steps.version.outputs.value }}
          assets: |
            soothe-vault*.zip
            source-with-envs-*.tar.gz
          fail-if-no-assets: false
          fail-if-no-release: false
      - name: Create or Update Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release Candidate (${{ steps.version.outputs.value }})
          prerelease: true
          draft: false
          tag_name: ${{ steps.version.outputs.value }}-rc
          generate_release_notes: true
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            apps/nodejs/extension/releases/soothe-vault-chromium-${{ steps.version.outputs.value }}.zip
            apps/nodejs/extension/releases/soothe-vault-firefox-${{ steps.version.outputs.value }}.zip
            source-with-envs-${{ steps.version.outputs.value }}.tar.gz
