name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - opened
      - edited

jobs:
  create-pre-release:
    # Only run the job if the PR is from the changeset-release branch
    if: startsWith(github.head_ref, 'changeset-release/')
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn
      - name: Build Extension Dependencies
        run: yarn turbo run build --filter=\!@poktscan/extension
      - name: Prepare Chromium Release Asset
        run: yarn release:chromium
      - name: Prepare Firefox Release Asset
        run: yarn release:firefox
      - name: Extract Extension Package Version
        uses: sergeysova/jq-action@v2.3.0
        id: version
        with:
          cmd: 'jq .version apps/nodejs/extension/package.json -r'
      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: rc${{ github.event.pull_request.number }}
          assets: 'soothe-vault*.zip'
          fail-if-no-assets: false
          fail-if-no-release: false
      - name: Create or Update Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release Candidate (${{ steps.version.outputs.value }})
          prerelease: true
          draft: false
          tag_name: ${{ steps.version.outputs.value }}-rc
          generate_release_notes: true
          fail_on_unmatched_files: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
              apps/nodejs/extension/releases/soothe-vault-chromium-${{ steps.version.outputs.value }}.zip
              apps/nodejs/extension/releases/soothe-vault-firefox-${{ steps.version.outputs.value }}.zip
