name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: write
jobs:
  release:
    # Only run this job if the pull request was merged and the source branch was a changeset-release branch
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'changeset-release/')
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Prepare source with envs
        run: |
          git ls-files > tar-include.txt
          echo "${{vars.ENV_FILE}}" > apps/nodejs/extension/.env
          echo "apps/nodejs/extension/.env" >> tar-include.txt
          # required by firefox on releases
          tar -czf source-with-envs.tar.gz -T tar-include.txt
      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies
        run: yarn
      - name: Build Extension Dependencies
        run: yarn turbo run build --filter=\!@soothe/extension
      - name: Prepare Chromium Release Asset
        run: yarn release:chromium
      - name: Prepare Firefox Release Asset
        run: yarn release:firefox
      - name: Extract Extension Package Version
        uses: sergeysova/jq-action@v2.3.0
        id: version
        with:
          cmd: 'jq .version apps/nodejs/extension/package.json -r'
      - name: Rename source-with-envs to include version
        run: |
          # rename to include version
          mv source-with-envs.tar.gz source-with-envs-${{ steps.version.outputs.value }}.tar.gz
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ steps.version.outputs.value }}
          prerelease: false
          draft: false
          tag_name: v${{ steps.version.outputs.value }}
          make_latest: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            apps/nodejs/extension/releases/soothe-vault-chromium-${{ steps.version.outputs.value }}.zip
            apps/nodejs/extension/releases/soothe-vault-firefox-${{ steps.version.outputs.value }}.zip
            source-with-envs-${{ steps.version.outputs.value }}.tar.gz
