name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release:
    # Only run this job if the pull request was merged and the title is 'Release Packages', this title is defined in the "version-packages.yml" workflow.
    if: github.event.pull_request.merged == true && github.event.pull_request.title == 'Release Packages'
    runs-on: ubuntu-latest
    env:
      LAVAMOAT_AUTO_POLICY: "false"
      PROVIDER_INFO_NAME: "Soothe Vault"
      PROVIDER_INFO_ICON: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTEyIiBoZWlnaHQ9IjUxMiIgdmlld0JveD0iMCAwIDUxMiA1MTIiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxnIGNsaXAtcGF0aD0idXJsKCNjbGlwMF8xNV8yNSkiPgo8cmVjdCB4PSIxMzIuNzQxIiB5PSIxMzIuNzQxIiB3aWR0aD0iMjQ2LjUxOSIgaGVpZ2h0PSIyNDYuNTE5IiBmaWxsPSIjRDlEOUQ5Ii8+CjxwYXRoIGZpbGwtcnVsZT0iZXZlbm9kZCIgY2xpcC1ydWxlPSJldmVub2RkIiBkPSJNMjU2IC0wLjYzMTgzNkw0NzggNzcuMDY4MlYyNTZDNDc4IDM0Ny42MiA0MjEuNzQ1IDQxMS42NjcgMzY5LjMwOSA0NTEuNDI3QzMyMy4zMTUgNDg1Ljk3OCAyNTYgNTEyLjYzMiAyNTYgNTEyLjYzMkMyNTYgNTEyLjYzMiAxODcuMTI1IDQ4NS4xMDQgMTQyLjY2OSA0NTEuNDA1QzkwLjI3NyA0MTEuNjg5IDM0IDM0Ny42NDIgMzQgMjU2LjAyMlY3Ny4wNjgyTDI1NiAtMC42MzE4MzZaTTE3MC41MjUgMTgzLjYwNUgzNDEuNDMxQzM1NS41NDcgMTgzLjYwNSAzNjcgMTcyLjIwMSAzNjcgMTU4LjA5QzM2NyAxNDMuOTc5IDM1NS41NDcgMTMyLjU3NSAzNDEuNDc1IDEzMi41NzVIMTcwLjUyNUMxNTYuNDA5IDEzMi41NzUgMTQ1IDE0My45NzkgMTQ1IDE1OC4wOUMxNDUgMTcyLjIwMSAxNTYuNDUzIDE4My42MDUgMTcwLjUyNSAxODMuNjA1Wk0xNzAuNTI1IDM1NC41NzVIMzIxLjAxMUMzMzIuMTUzIDM1NC41NzUgMzQyLjg5NiAzNTAuOTgxIDM1MS4yNDEgMzQ0LjM3QzM2MS4yMjkgMzM2LjUxNSAzNjYuOTU2IDMyNS4wNjcgMzY2Ljk1NiAzMTIuOTUzVjI1OC45MDZDMzY2Ljk1NiAyNDYuNzkzIDM2MS4yMjkgMjM1LjM0NCAzNTEuMjQxIDIyNy40OUMzNDIuODk2IDIyMC45MjMgMzMyLjE1MyAyMTcuMzI5IDMyMS4wMTEgMjE3LjMyOUgxNzAuNTI1QzE1Ni40MDkgMjE3LjMyOSAxNDUgMjI4LjczMyAxNDUgMjQyLjg0M0MxNDUgMjU2Ljk1NCAxNTYuNDUzIDI2OC4zNTggMTcwLjUyNSAyNjguMzU4SDI5OC41OTNDMjk4LjU5MyAyNjguMzU4IDMxNi44ODIgMjY2Ljg5NCAzMTYuODgyIDI4NS4zMDlDMzE2Ljg4MiAzMDQuMTY3IDI5OC41OTMgMzAzLjU0NiAyOTguNTkzIDMwMy41NDZIMTcwLjUyNUMxNTYuNDA5IDMwMy41NDYgMTQ1IDMxNC45NSAxNDUgMzI5LjA2MUMxNDUgMzQzLjE3MSAxNTYuNDUzIDM1NC41NzUgMTcwLjUyNSAzNTQuNTc1WiIgZmlsbD0iIzE1MkE0OCIvPgo8L2c+CjxkZWZzPgo8Y2xpcFBhdGggaWQ9ImNsaXAwXzE1XzI1Ij4KPHJlY3Qgd2lkdGg9IjUxMiIgaGVpZ2h0PSI1MTIiIGZpbGw9IndoaXRlIi8+CjwvY2xpcFBhdGg+CjwvZGVmcz4KPC9zdmc+Cg=="
      PROVIDER_INFO_RDNS: io.trustsoothe
      WPOKT_TESTNET_API_BASE_URL: https://testnet-wpokt.vercel.app/api
      WPOKT_MAINNET_API_BASE_URL: https://wpokt.network/api
      PRICE_API_BASE_URL: https://api.coingecko.com/api/v3/
      NETWORKS_CDN_URL: https://poktscan-v1.nyc3.cdn.digitaloceanspaces.com/networks.json
      ASSETS_CDN_URL: https://poktscan-v1.nyc3.cdn.digitaloceanspaces.com/assets.json
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn
      - name: Build Extension Dependencies
        run: yarn turbo run build --filter=\!@poktscan/extension
      - name: Prepare Chromium Release Asset
        run: yarn release:chromium
      - name: Prepare Firefox Release Asset
        run: yarn release:firefox
      - name: Extract Extension Package Version
        uses: sergeysova/jq-action@v2.3.0
        id: version
        with:
          cmd: 'jq .version apps/nodejs/extension/package.json -r'
      - name: Create Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.value }}
          release_name: v${{ steps.version.outputs.value }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
      - name: Upload Chromium Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: apps/nodejs/extension/releases/soothe-vault-chromium.zip
          asset_name: soothe-vault-chromium-v${{ steps.version.outputs.value }}.zip
          asset_content_type: application/zip
      - name: Upload Firefox Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: apps/nodejs/extension/releases/soothe-vault-firefox.zip
          asset_name: soothe-vault-firefox-v${{ steps.version.outputs.value }}.zip
          asset_content_type: application/zip
