name: Release Packages

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          # this is the default value for the title however, It's being set explicitly here because it's also used in the "release.yml" workflow.
          title: 'Release Packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
